### ISSUE TITLE
Language select button

### ISSUE THREAD

**Issue by TheGrits** [scratchdesignstudio/info#1]
![ic_language_white_24dp_2x](https://cloud.githubusercontent.com/assets/12952370/12951928/a53edac0-cfe2-11e5-8c43-201104b583a5.png)

Google is awesome for making these available to developers: https://design.google.com/icons/
FYI the image is white, so you won't really see it. Here's the black version of it:
![ic_language_black_24dp_2x](https://cloud.githubusercontent.com/assets/12952370/12952020/01aa8caa-cfe3-11e5-86d1-9f32d4b6676a.png)

**Comment by TheGrits** [comment]
I'm assigning you to it because I don't have Git and thus can't upload .png files.

**Comment by hyperobject** [comment]
Added.

**Comment by TheGrits** [comment]
After thinking it over again, I discovered we didn't really need it. But thanks anyway!
