### ISSUE TITLE
New Translations

### ISSUE THREAD

**Issue by LiFaytheGoblin** [scratchdesignstudio/info#11]
Hi!

We need new Translations for the next SDS.

To beginn with we have this submission:
https://docs.google.com/document/d/1O1A9TIh878cqBPgRiUTt4COhvGgq04n3sovsjNHhjMM/edit?usp=sharing 

Greetings,
Linda

**Comment by TheGrits** [comment]
Good call. I'll leave the translators of the previous SDS a note on their profiles.

Thanks for the reminder!

**Comment by Leo2910** [comment]
Hi! -MysteryMaker- from Scratch here! I am no longer active on Scratch but I'll still be willing to translate the descriptions to help the SDS! :) - Leo J 
Date: Tue, 19 Apr 2016 05:18:44 -0700

**Comment by Leo2910** [comment]
Hi everyone,

I love the SDS and I will continue helping the SDS!

I have once again translated the description of the SDS ~ Make Music! This time, I have done it in 2 languages, Turkish and Bulgarian!

Turkish: http://pastebin.com/W0ELhBHi
Bulgarian: http://pastebin.com/KVT04TgJ

Kind Regards,
Leo

**Comment by TheGrits** [comment]
@Leo2910 Thanks. I have just added Turkish, I'll get to Bulgarian tomorrow. Thanks again for your work!

**Comment by Leo2910** [comment]
You're very welcome, TheGrits! I love helping and supporting the amazing SDS!

Date: Mon, 2 May 2016 20:14:42 -0700

**Comment by TheGrits** [comment]
@Leo2910 Just verifying, you did **not** use Google Translate for Bulgarian, right? The translations appear to be exactly the same.

**Comment by Leo2910** [comment]
No, I did not use Google Translate. I do not agree with cheating and never will cheat in my entire lie. I have not cheated and used Google Translate. 
Date: Tue, 3 May 2016 04:52:20 -0700

**Comment by TheGrits** [comment]
@Leo2910 I trust you, I was just curious because it was the exact same as the Google translation. I'll add the Bulgarian translation now.

**Comment by TheGrits** [comment]
@Leo2910 Because you translated it from the current SDS's description, not all of the needed description is there. Please use this site for the lines, it should make translating a lot easier: http://scratchdesignstudio.github.io/translate-formatter/

**Comment by Leo2910** [comment]
Ok, it is very that you trust me! I understand that you're an official SDS curator and can't add any translations from Google Translate. Thank you! :) 
Date: Tue, 3 May 2016 12:48:44 -0700

**Comment by Leo2910** [comment]
What else do I need to translate? I don't get how to use that link.

Date: Tue, 3 May 2016 12:59:42 -0700

**Comment by Leo2910** [comment]
Ok, it is very that you trust me! I understand that you're an official SDS curator and can't add any translations from Google Translate. Thank you! :) 
Date: Tue, 3 May 2016 12:48:44 -0700

**Comment by TheGrits** [comment]
@Leo2910 Does this page that I made help? https://github.com/scratchdesignstudio/translate-formatter/wiki/How-to-use-the-translate-formatter-Site

The reason I'm asking you to use this site is because we have designed it to automatically format the result, as well as having all of the lines needed. This allows us to get the translation up on the site with minimal issues.

**Comment by LiFaytheGoblin** [comment]
Um, I don't mean to be rude and I'm really sorry this is happening, but here's what a friend of mine (he's Bulgarian and a native speaker) wrote about the Bulgarian translation: 
"Yep, it's Bulgarian but it is obviously translated with google"
:\
