### ISSUE TITLE
Have a way to link directly to a specific language

### ISSUE THREAD

**Issue by Scimonster** [scratchdesignstudio/info#22]
Perhaps with a hash in the URL, so like i could go to http://scratchdesignstudio.github.io/info/#Deutsch and have it load the German translation. This would be useful for providing links.

**Comment by TheGrits** [comment]
@Scimonster That's a fantastic idea! Thank you for the suggestion!

**Comment by TheGrits** [comment]
@technoboy10 We can read the hash of the URL with [`location.hash`](http://www.w3schools.com/jsref/prop_loc_hash.asp). With the existing way we are currently [referencing languages](https://github.com/scratchdesignstudio/info/blob/gh-pages/main.js#L28) it's going to be a little tricky using the [languageSelect](https://github.com/scratchdesignstudio/info/blob/gh-pages/main.js#L34-L41) function we currently have set up. Any ideas on how to get around this?

**Comment by Scimonster** [comment]
Try just passing a language code to the languageSelect function. Then set up the hash to just use a language code, so `#de`. Since all the translations are loaded with the page (not AJAX or anything fancy) this should just work.

**Comment by TheGrits** [comment]
Completed in https://github.com/scratchdesignstudio/info/commit/521df6be9c8b3ae76b0d433238ee8c1713684412 and https://github.com/scratchdesignstudio/info/commit/ae14048a5190a14ebdcf3c437e6eb4ad6d9b23cf!

Thank you for your excellent suggestion, I'm glad it could be implemented!
