### ISSUE TITLE
spanish translations - sync issues?

### ISSUE THREAD

**Issue by LiFaytheGoblin** [scratchdesignstudio/info#23]
Wahhhh, help, I think I made a mistake by not pulling changes from GitHub before updating the language file to have an up to date spanish translation. I'm confused, it says there is a sync issue... Help?
@TheGrits

**Comment by TheGrits** [comment]
@LiFaytheGoblin Where are you trying to merge from? (It doesn't look like you have any fork or another branch) The Sync issue comes up when your version of the repo is outdated and you're trying to push to the up to date version of the repo. You could try `git pull upstream master`

If you have the Spanish translation formatted already, I could also merge it in on my side.
