### ISSUE TITLE
The button is below the bar

### ISSUE THREAD

**Issue by TheGrits** [scratchdesignstudio/info#3]
The button is in the middle of the screen below the green bar. Click it, and the menu appears on the right side of the screen. I gotta go right now, so feel free to figure it out.

**Comment by hyperobject** [comment]
Not happening for me in Chrome 50, what browser are you using?

**Comment by TheGrits** [comment]
Chrome 48

**Comment by TheGrits** [comment]
I just checked this morning and it is now in the bar.
