### ISSUE TITLE
Globe icon beside language dropdown?

### ISSUE THREAD

**Issue by towerofnix** [scratchdesignstudio/info#35]
I'm thinking having a globe next to the language dropdown would be useful for calling attention to it, especially for people who can't read English.

**Comment by TheGrits** [comment]
@liam4 I like your thinking, I'll try to figure out a solution this morning.

**Comment by TheGrits** [comment]
@liam4 Done, feel free to tell me what you think!

**Comment by towerofnix** [comment]
Hmm.. the icon positioning seems a bit, well, lack-luster:

![Misaligned](https://cloud.githubusercontent.com/assets/9948030/24829357/334cfddc-1c46-11e7-9c38-17612c28f2f9.png)

Is that how it looks on your screen as well? I'd think to add a bit of margin between the icon and the dropdown. I'd also have vertically-centered it, so it looks more aligned with the text.

**Comment by towerofnix** [comment]
>Let's see if this works

You *did* test it locally, didn't you?! :shipit:

**Comment by TheGrits** [comment]
@liam4 Just pushed a commit about 2 minutes ago that adds a little bit of a buffer between them, try hard refreshing. (CTRL + click refresh)

**Comment by TheGrits** [comment]
@liam4 lol I'm a Chromebook user, so I can't render things properly on local images. ¯\_(ツ)_/¯

**Comment by TheGrits** [comment]
@liam4 I'm not entirely sure how to vertical align the icon, I have that issue too. I figured something off-centre is better than nothing though.

**Comment by towerofnix** [comment]
I'll take a look and see if I can make it work.. with local testing :P

**Comment by TheGrits** [comment]
@liam4 haha go for it

I think I found a possible solution with `vertical-align:middle;` If I apply that to the text in the button theoretically it should centre out.
