### ISSUE TITLE
We need translations

### ISSUE THREAD

**Issue by TheGrits** [scratchdesignstudio/info#4]
I think the site is at a point that the next step is to get translations.

I'm going to see if @LiFaytheGoblin would be willing to help us with this, we only really need two languages to test it out for now.

**Comment by LiFaytheGoblin** [comment]
Also I suggest we don't translate the title? We've never translated the title in the German Wiki...

**Comment by hyperobject** [comment]
@TheGrits We may need to split the description into several parts in the source code so we can decide what to translate/load automagically. I'm thinking studio title, unique description, and then the standard copy-pasted stuff. Sound good?

**Comment by TheGrits** [comment]
@technoboy10 Way ahead of you. Check the js file. :stuck_out_tongue:

**Comment by TheGrits** [comment]
@LiFaytheGoblin Ok, sounds good. (It'll be easier on us too!)

**Comment by hyperobject** [comment]
Second thing to discuss: how are we going to store the translations? I've got them in a separate JSON file so that the main.js file doesn't get super big and messy, but it's not ideal because of all the links and newlines we have in the description.

**Comment by TheGrits** [comment]
@technoboy10 Normally we don't have links in the 'unique description', so it shouldn't be too bad for that. I can't think of any solutions of the top of my head for the links though...

**Comment by hyperobject** [comment]
@TheGrits Right now I have it so that the string for the unique description has all the HTML elements in it, which works but I'm not sure it's ideal.

**Comment by TheGrits** [comment]
@technoboy10 @LiFaytheGoblin No point translating the current SDS's unique description, we're ready to go live with the new one.

**Comment by TheGrits** [comment]
@LiFaytheGoblin @technoboy10 What do you guys think about getting some help from bilingual Scratchers? I feel like they could help us a lot.

**Comment by hyperobject** [comment]
I'd be in favor of that.

**Comment by LiFaytheGoblin** [comment]
+1

**Comment by TheGrits** [comment]
@LiFaytheGoblin @technoboy10 Do you guys know anyone who can speak French and English fluently?

**Comment by LiFaytheGoblin** [comment]
@TheGrits Smrman on Scratch has helped me out with translation before and is working on the french wiki...

**Comment by TheGrits** [comment]
@LiFaytheGoblin I just sent him a message, we'll see what he says.

**Comment by TheGrits** [comment]
@LiFaytheGoblin @technoboy10 I have just finished adding the translations for Spanish and French. Big :+1: to mundofinky and Smrman!

**Comment by hyperobject** [comment]
@TheGrits Awesome! Should we start linking to it in the SDS description?

**Comment by TheGrits** [comment]
@technoboy10 I think we should probably get the German translation done before we link it to the description.

**Comment by hyperobject** [comment]
Oops, didn’t notice that German wasn’t done just yet.

**Comment by LiFaytheGoblin** [comment]
Argh since the last update, my desktop github is broken. It doesn't want to sync anymore. No idea why... I'll post the German translation here as soon as I have it (there's a Scratcher who wants to help with it)... 

Edit: ARGH that git shell doesn't work either >.< Maybe my firewall... Oh noo >(

Edit: Yep, it was the firewall, problem solved^^

**Comment by hyperobject** [comment]
@TheGrits Now that we have an easier way for people to create translations, should we post a link to the formatter site somewhere on Scratch (or other sites - I'd be happy to post it on Twitter but I don't know if we'd rather source translations from Scratch users directly)?

**Comment by TheGrits** [comment]
@technoboy10 :+1: I think it would probably be best if we only have Scratch users translating. We could always try to post the link elsewhere if we aren't getting enough translations.

**Comment by Leo2910** [comment]
I will translate it to Turkish!

**Comment by hyperobject** [comment]
@Leo2910 Awesome! Let us know when you've finished it. :)

**Comment by Leo2910** [comment]
Ok! However, I do not really understand how to translate it and where to submit my translation.

Date: Sun, 20 Mar 2016 09:33:52 -0700

**Comment by hyperobject** [comment]
@Leo2910 Fill out the translation on http://scratchdesignstudio.github.io/translate-formatter/ and copy the result at the bottom into a text file and upload it to either Github or something like pastebin.com.

**Comment by Leo2910** [comment]
Oh, ok, that is easy! Thanks for the advice, Connor! :D

Date: Sun, 20 Mar 2016 09:38:56 -0700

**Comment by Leo2910** [comment]
Hi there, guys! I have made the Turkish translation for the SDS! Here is the translation: http://pastebin.com/SJyihPtC

**Comment by TheGrits** [comment]
@Leo2910 Thanks for your hard work, but there's a little problem.
@technoboy10 and I designed the translate-formatter site to make it as easy as possible for the translator and us to add translations to the site. It looks like you didn't use the result from the bottom of the site, or something went wrong with pastebin.

Thanks again for your help, I hope we can get it to work!

**Comment by Leo2910** [comment]
Why? What is wrong with it? I can help fix it if you want. Can`t you just copy and paste?

**Comment by TheGrits** [comment]
Yes and no.

The result from the bottom of this page: http://scratchdesignstudio.github.io/translate-formatter/ is specially formatted with special characters for new lines and links.

What the pastebin had was the unformatted version, which means we would need to format it by hand.

**Comment by TheGrits** [comment]
@Leo2910 
I just realized that we could copy and paste the unformatted result into the formatter then copy and paste the result from the formatter. (If you don't understand what I'm saying I can probably do it tomorrow)

**Comment by Leo2910** [comment]
@TheGrits I organised it into sections such as it is now in the current SDS studio. Ok, yes, I suppose we could do that. I am doing this because I want to show my determination to help in the community. I can get you some more other languages, if you would like. :D

**Comment by hyperobject** [comment]
@Leo2910 There should be a section at the bottom of the formatter site labeled 'Result' with a text box, did that show up for you?

**Comment by Leo2910** [comment]
No

Date: Sun, 20 Mar 2016 11:07:15 -0700

**Comment by Leo2910** [comment]
I translated it straight from Remix-A-Thon to pastebin.com! :D I did not use the translate formatter.

Date: Sun, 20 Mar 2016 11:07:15 -0700

**Comment by hyperobject** [comment]
Ah, ok. If you could use the formatter site for any other languages you
translate, it makes it a little easier for us to add your translation to
the info site. :)

**Comment by Leo2910** [comment]
Ok.

Date: Sun, 20 Mar 2016 11:13:06 -0700

**Comment by hyperobject** [comment]
@Leo2910 I've added your translation to the site! Can you translate these phrases as well? (for some site-specific things)

1) Translated by -MysteryMaker-
2) The SDS is curated by

Thanks! :D

**Comment by Leo2910** [comment]
1) -MysteryMaker- Çeviri
2) SDS küratörlüğünü
There you go! You`re very welcome! :D
Date: Sun, 20 Mar 2016 16:46:26 -0700

**Comment by TheGrits** [comment]
@Leo2910 Thanks, I'll add the last bits! :)

**Comment by Leo2910** [comment]
You`re welcome! :D

Date: Mon, 21 Mar 2016 03:53:24 -0700

**Comment by TheGrits** [comment]
Closing becuase we have a new issue for the new SDS.
