### ISSUE TITLE
"sds" in header

### ISSUE THREAD

**Issue by hyperobject** [scratchdesignstudio/info#6]
@TheGrits I'm not super happy with how the "sds" part of the header looks right now - I tried changing the font of it to the Scratch font, but it looked pretty squished. Using "Scratch Design Studio" looks pretty nice, but it might be another string we'd have to translate (not super hard though, since a lot of the international Scratch wikis have pages about the SDS that we could just grab the title from). Thoughts?

**Comment by TheGrits** [comment]
Honestly I don't mind it the way it is now. What's with the purple SDS title though?

**Comment by hyperobject** [comment]
@TheGrits We may need to translate the header anyway - different languages have different abbreviations.

**Comment by TheGrits** [comment]
@technoboy10 Yeah, I found that out when I looked on the French version of the Scratch homepage. I'm not sure if it's worth it to translate the SDS abbreviation though, as I'm sure most people know what SDS means in English. (For example, I think most French speakers probably associate the studio with the abbreviation SDS)

**Comment by hyperobject** [comment]
Yup, that makes sense. Closing.
